require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec

# METRICS
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 16
Metrics/ClassLength:
  Exclude:
    - 'app/models/**/*'
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'app/views/admin/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

# STYLE
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'config.ru'
    - 'spec/**/*'
    - 'app/views/**/*.json.jbuilder'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/HashSyntax:
  EnforcedShorthandSyntax: consistent
Style/NumericLiterals:
  Enabled: false

# LAYOUT
Layout/LineLength:
  Max: 124
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# LINT
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

# RSpec
RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - 'spec/system/**/*'
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/system/**/*'

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - '.pryrc'
  NewCops: enable
