development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: s95_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: s95_production
